@echo off
echo Starting EcoFinds Backend...
cd /d "%~dp0backend"
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Starting server...
python server.py
pause
